// Image listing constants
export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST';
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS';
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL';

//Page
export const INCREMENT_PAGE = 'INCREMENT_PAGE';

//User
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REG_REQUEST = 'USER_REG_REQUEST';
export const USER_REG_SUCCESS = 'USER_REG_SUCCESS';
export const USER_REG_FAIL = 'USER_REG_FAIL';

//set fav wallpaper
export const SET_FAV_WALLPAPER_REQUEST = 'SET_FAV_WALLPAPER_REQUEST';
export const SET_FAV_WALLPAPER_SUCCESS = 'SET_FAV_WALLPAPER_SUCCESS';
export const SET_FAV_WALLPAPER_FAIL = 'SET_FAV_WALLPAPER_FAIL';

export const GET_FAV_WALLPAPER_REQUEST = 'GET_FAV_WALLPAPER_REQUEST';
export const GET_FAV_WALLPAPER_SUCCESS = 'GET_FAV_WALLPAPER_SUCCESS';
export const GET_FAV_WALLPAPER_FAIL = 'GET_FAV_WALLPAPER_FAIL';
